### ISSUE TITLE
filter item's `not` field is required and not optional

### ISSUE THREAD

**Issue by robxbob** [autoinvent/magql#113]
not is recognized as being a required field when it should be optional

```graphql
FilterItem {
  not: Boolean! = false
}
```

**Comment by davidism** [comment]
The definition appears correct, I can submit a filter without the `not` field and it does not raise an error. The arg is required, which means it must have a value by the time it resolves, but it has a default in case it's not actually given. Using the task example in the repo, the following query succeeds:

```graphql
query {
  task_list(filter: {path: "message", op: "eq", value: "test"}) {
    items {
      id
      message
    }
  }
}
```
